installer:
  release: "v0.5.3"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:22b5e4e1-325-10252"
  devtron:
    image: "quay.io/devtron/hyperion:51c5b59b-280-10346"
    cicdImage: "quay.io/devtron/devtron:51c5b59b-326-10345"
  argocdDexServer:
    image: "ghcr.io/dexidp/dex:v2.30.2"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v2.4.0"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:9c933d29-149-10140"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "51c5b59bf561191344e85c653c6c5dfdd8ee7713"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "51c5b59bf561191344e85c653c6c5dfdd8ee7713"
